kind: "DataContract"
apiVersion: "v3.1.0"
id: "urn:datacontract:orders:v1"
name: "orders_data_contract"
version: "1.0.0"
status: "active"
domain: "sales"
tags:
  - "demo"
description:
  purpose: "Provides order and line item data for analytics and reporting"
  usage: "Used by analytics team for sales analysis and business intelligence"
  limitations: "Contains only the last 2 years of data"
  customProperties:
    - property: "sensitivity"
      value: "secret"
      description: "Data contains personally identifiable information"
  authoritativeDefinitions:
    - url: "https://entropy-data.com/policies/gdpr-compliance"
      type: "GDPR Policy"
      description: "GDPR compliance policy for handling customer data"
schema:
  - name: "orders"
    logicalType: "object"
    physicalType: "table"
    description: "All successful and cancelled web-shop orders since 2020-01-01"
    quality:
      - name: "Row count"
        metric: "rowCount"
        mustBeGreaterThan: 100000
        description: "If the row count is less than 100,000, something is wrong"
        dimension: "completeness"
    properties:
      - name: "order_id"
        businessName: "Order Identifier"
        logicalType: "string"
        physicalType: "uuid"
        description: "Technical ID for the order"
        required: true
        primaryKey: true
        classification: "internal"
        examples:
          - "123e4567-e89b-12d3-a456-426614174000"
      - name: "customer_id"
        businessName: "Customer Identifier"
        logicalType: "string"
        physicalType: "text"
        description: "Reference to customer who placed the order"
        required: true
        classification: "public"
        examples:
          - "1000000001"
      - name: "order_total"
        businessName: "Total Order Amount"
        logicalType: "integer"
        physicalType: "integer"
        description: "Total order amount in cent"
        required: true
        classification: "internal"
        examples:
          - 9999
        logicalTypeOptions:
          minimum: 0
      - name: "order_timestamp"
        businessName: "Order Date"
        logicalType: "timestamp"
        physicalType: "timestamptz"
        description: "Date and time when order was placed in UTC time zone"
        required: true
        partitioned: true
        partitionKeyPosition: 1
        classification: "internal"
        examples:
          - "2025-11-23 11:40:26.456654+00"
      - name: "order_status"
        businessName: "Status"
        description: "The business status of the order"
        logicalType: "string"
        physicalType: "TEXT"
        examples:
          - "shipped"
        quality:
          - type: "library"
            description: "Ensure that there are no other status values."
            metric: "invalidValues"
            arguments:
              validValues:
                - "pending"
                - "paid"
                - "processing"
                - "shipped"
                - "delivered"
                - "cancelled"
                - "refunded"
            mustBe: 0
  - name: "line_items"
    physicalType: "table"
    description: "Details for each item in an order"
    properties:
      - name: "line_item_id"
        logicalType: "string"
        description: "Unique identifier for the line item"
        physicalType: "UUID"
        examples:
          - "12c9ba21-0c44-4e29-ba72-b8fd01c1be30"
        logicalTypeOptions:
          format: "uuid"
        required: true
        primaryKey: true
      - name: "sku"
        logicalType: "string"
        businessName: "Stock Keeping Unit"
        description: "Identifier for the purchased product"
        physicalType: "TEXT"
        examples:
          - 111222333
        required: true
      - name: "price"
        logicalType: "integer"
        description: "Price in cents for this line item including tax"
        physicalType: "INTEGER"
        examples:
          - 9999
        required: true
      - name: "order_id"
        required: false
        primaryKey: false
        logicalType: "string"
        physicalType: "uuid"
        description: "Reference to the order that this line item belongs to"
        relationships:
          - type: "foreignKey"
            to: "orders.order_id"
servers:
  - server: "postgres"
    environment: "demo"
    type: "postgres"
    host: "aws-1-eu-central-2.pooler.supabase.com"
    port: 6543
    database: "postgres"
    schema: "dp_orders_v1"
team:
  name: "Sales Analytics Team"
  description: "Team responsible for managing and maintaining sales order data"
  members:
    - username: "sarah.chen@entropy-data.com"
      name: "Sarah Chen"
      role: "Data Product Owner"
      description: "Responsible for the overall data product strategy and roadmap"
    - username: "mike.johnson@entropy-data.com"
      name: "Mike Johnson"
      role: "Data Steward"
      description: "Ensures data quality and maintains data governance standards"
    - username: "lisa.martinez@entropy-data.com"
      name: "Lisa Martinez"
      role: "Data Engineer"
      description: "Manages data pipelines and technical implementation"
support:
  - channel: "#sales-data-support"
    tool: "teams"
    url: "https://teams.microsoft.com/l/channel/sales-data-support"
    scope: "interactive"
    description: "Teams channel for data contract support and questions"
  - channel: "#data-contracts"
    tool: "slack"
    url: "https://entropy-data.slack.com/archives/C123456789"
    invitationUrl: "https://entropy-data.slack.com/join/shared_invite/abc123xyz"
    scope: "interactive"
    description: "Slack channel for real-time support and collaboration"
  - channel: "SALES Board"
    tool: "ticket"
    url: "https://entropy-data.atlassian.net/jira/software/projects/SALES/boards/1"
    scope: "issues"
    description: "Jira board for requesting new data products or submitting bugs"
slaProperties:
  - property: "freshness"
    value: 24
    unit: "hours"
    element: "orders.order_date"
    driver: "operational"
    description: "Order data is refreshed within 24 hours of order placement"
  - property: "retention"
    value: 10
    unit: "years"
    driver: "regulatory"
    description: "Order and line item data retained for 10 years for compliance purposes"
